CLASS zcx_bw_trfn_tester DEFINITION
  PUBLIC
  INHERITING FROM cx_static_check
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS zcx_bw_trfn_tester IMPLEMENTATION.
ENDCLASS.
