CLASS zcx_bw_trfn_tester DEFINITION
INHERITING FROM CX_STATIC_CHECK
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcx_bw_trfn_tester IMPLEMENTATION.
ENDCLASS.
