CLASS zcx_bw_trfn_tester DEFINITION
INHERITING FROM cx_static_check
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS zcx_bw_trfn_tester IMPLEMENTATION.
ENDCLASS.
